name: Automação de Commits da IA

on:
  workflow_dispatch:
    inputs:
      task_description:
        description: 'Descreva a tarefa para a IA'
        required: true
        default: 'Melhorar o código'

permissions: write-all

jobs:
  ai-development:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          ref: beta
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Executar script de IA
        run: node scripts/ai-development.js
        env:
          TASK_DESCRIPTION: ${{ github.event.inputs.task_description }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configurar Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Commit das alterações
        run: |
          git add .
          git diff --staged --quiet || git commit -m "AI: ${{ github.event.inputs.task_description }}"
      
      - name: Push para beta
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: beta 